apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: wkld-external-secret
  namespace: tap-app-config-properties
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: gitops_ssh_secret
    value: git-credentials
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: inclusion-db
  source:
    git:
      ref:
        branch: main
      url: https://github.com/timosalm/emoji-inclusion.git