apiVersion: "config.apps.tanzu.vmware.com/v1alpha4"
kind: ConfigurationSource
metadata:
  name: db-binding-source
  namespace: tap-app-config-properties
spec:
  backends:
    - type: git
      uri: https://github.com/timosalm/tap-app-config-properties-sample
      searchPaths: 
      - externalized-dev-configuration
---
apiVersion: "config.apps.tanzu.vmware.com/v1alpha4"
kind: ConfigurationSlice
metadata:
  name: db-binding-slice
  namespace: tap-app-config-properties
spec:
  configurationSource: db-binding-source
  content:
  - inclusion/production
  - inclusion/default
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: db-binding-config-claim
  namespace: tap-app-config-properties
spec:
  ref:
    apiVersion: config.apps.tanzu.vmware.com/v1alpha4
    kind: ConfigurationSlice
    name: db-binding-slice
    namespace: tap-app-config-properties
