apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-with-encryption-key
  namespace: tap-app-config-properties
stringData:
  basicauth.username: GIT-USERNAME
  basicauth.password: GIT-PASSWORD
  encryption.key: MY-KEY