#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-with-encryption-key
  namespace: tap-app-config-properties
stringData:
  basicauth.username: #@ data.values.ops_git_repo.username
  basicauth.password: #@ data.values.ops_git_repo.password
  encryption.key: #@ data.values.ops_git_repo.encryption_key