#@ load("@ytt:data", "data")
---
apiVersion: "config.apps.tanzu.vmware.com/v1alpha4"
kind: ConfigurationSource
metadata:
  name: acs-seperation-encrypted-source
  namespace: tap-app-config-properties
spec:
  backends:
    - type: git
      uri: https://github.com/timosalm/tap-app-config-properties-sample
      searchPaths: 
      - externalized-dev-configuration
    - type: git
      uri:  #@ data.values.ops_git_repo.https_url
      defaultLabel: encrypted
      secretRef: 
        name: git-credentials-with-encryption-key
        namespace: tap-app-config-properties
---
apiVersion: "config.apps.tanzu.vmware.com/v1alpha4"
kind: ConfigurationSlice
metadata:
  name: acs-seperation-encrypted-slice
  namespace: tap-app-config-properties
spec:
  configurationSource: acs-seperation-encrypted-source
  content:
  - inclusion/production
  - inclusion/default
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: acs-seperation-encrypted-config-claim
  namespace: tap-app-config-properties
spec:
  ref:
    apiVersion: config.apps.tanzu.vmware.com/v1alpha4
    kind: ConfigurationSlice
    name: acs-seperation-encrypted-slice
    namespace: tap-app-config-properties
